# Generated by Django 5.1.5 on 2025-02-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0002_to_professoravailability_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professoravailability',
            old_name='pofessor',
            new_name='professor',
        ),
    ]
