# Generated by Django 5.1.5 on 2025-02-05 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0003_rename_pofessor_professoravailability_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professoravailability',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edt.professor'),
        ),
    ]
