# Generated by Django 5.1.5 on 2025-02-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0004_alter_professoravailability_professor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfessorAvailability',
            new_name='Edt',
        ),
    ]
